### ISSUE TITLE
Close Window

### ISSUE THREAD

**Issue by altair984** [TaureHorn/FoundryVTT_ActiveCharacterPortrait#2]
Hi, would it be possible to add a method so that when you click again on the icon to activate the window, if it is active, it closes it or a button to close it? sometimes it is annoying to have the window open all the time when you want to do certain scenes.

**Comment by TaureHorn** [comment]
Absolutely. I had intended that if you wanted it closed, you just used the Esc key. But I realise that's kinda annoying. I'll add the close back in :)

**Comment by TaureHorn** [comment]
close button added in v.1.15

theres a chance that updating may not work properly. in which case you'll have to uninstall and reinstall instead.

**Comment by altair984** [comment]
Thanks :)
